apiVersion: apps/v1
kind: Deployment
metadata:
  name: live-app-backend
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: app
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
