apiVersion: v1
kind: Secret
metadata:
  name: live-app-secret-example
  labels:
    app.kubernetes.io/name: live-app-backend
    app.kubernetes.io/component: secret
type: Opaque
stringData:
  JWT_SECRET: example-change-me
  DATABASE_PASSWORD: example-change-me
  SMS_PROVIDER_API_KEY: example-change-me
